### ISSUE TITLE
All modules should be Resource

### ISSUE THREAD

**Issue by lorandszakacs** [busymachines/pure-movie-server#30]
https://github.com/busymachines/pure-movie-server/blob/master/pms-utils/core/src/main/scala/pms/core/Module.scala 

is completely broken, memoization definitely does not work. And everything should be resources, really. That way we can build our entire server as a resource, that gets cleaned up nicely on startup.

**Comment by alexandrustana** [comment]
I guess this  can be closed now 🙂

**Comment by lorandszakacs** [comment]
closed by #33
